# Generated by Django 3.2.8 on 2021-11-11 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estilo',
            fields=[
                ('id_est', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('desc', models.CharField(max_length=4000)),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Ocasion',
            fields=[
                ('id_oc', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=4000)),
            ],
        ),
        migrations.CreateModel(
            name='Prenda',
            fields=[
                ('id_pr', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('disenador', models.CharField(max_length=40)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('talla', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], max_length=1)),
                ('origen', models.CharField(max_length=40)),
                ('cuidados', models.CharField(max_length=40)),
                ('materiales', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id_out', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('desc', models.CharField(max_length=4000)),
                ('precio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outfits', to='outfitShowroomApp.estilo')),
                ('ocasiones', models.ManyToManyField(related_name='outfitsocasiones', to='outfitShowroomApp.Ocasion')),
                ('prendas', models.ManyToManyField(related_name='outfitsprendas', to='outfitShowroomApp.Prenda')),
            ],
        ),
    ]
