# Generated by Django 3.2.8 on 2021-11-11 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitShowroomApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prenda',
            name='tipo',
            field=models.CharField(choices=[('null', 'null'), ('Abrigo', 'Abrigo'), ('Chaqueta', 'Chaqueta'), ('Zapatos', 'Zapatos'), ('Camisa', 'Camisa'), ('Pantalón', 'Pantalón'), ('Blazer', 'Blazer'), ('Camisa', 'Camisa'), ('Top', 'Top'), ('Camiseta', 'Camiseta'), ('Sudadera', 'Sudadera'), ('Accesorio', 'Accesorio'), ('Vestido', 'Vestido')], default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='talla',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large'), ('U', 'Unique Size')], max_length=1),
        ),
    ]
