# Generated by Django 3.2.8 on 2021-11-11 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitShowroomApp', '0002_auto_20211111_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prenda',
            name='tipo',
        ),
        migrations.AddField(
            model_name='prenda',
            name='tipo_prenda',
            field=models.CharField(choices=[('null', 'null'), ('Abrigo', 'Abrigo'), ('Chaqueta', 'Chaqueta'), ('Zapatos', 'Zapatos'), ('Camisa', 'Camisa'), ('Pantalón', 'Pantalón'), ('Blazer', 'Blazer'), ('Camisa', 'Camisa'), ('Top', 'Top'), ('Camiseta', 'Camiseta'), ('Sudadera', 'Sudadera'), ('Accesorio', 'Accesorio'), ('Vestido', 'Vestido')], default='null', max_length=100),
        ),
    ]
