# Generated by Django 3.2.8 on 2021-12-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitShowroomApp', '0003_auto_20211111_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estilo',
            name='nombre',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='ocasion',
            name='nombre',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='nombre',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='ocasiones',
            field=models.ManyToManyField(to='outfitShowroomApp.Ocasion'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='prendas',
            field=models.ManyToManyField(to='outfitShowroomApp.Prenda'),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='cuidados',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='disenador',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='materiales',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='nombre',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='origen',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='prenda',
            name='tipo_prenda',
            field=models.CharField(choices=[(' ', ' '), ('Abrigo', 'Abrigo'), ('Accesorio', 'Accesorio'), ('Blazer', 'Blazer'), ('Body', 'Body'), ('Botines', 'Botines'), ('Camisa', 'Camisa'), ('Camiseta', 'Camiseta'), ('Cazadora', 'Cazadora'), ('Chaqueta', 'Chaqueta'), ('Jeans', 'Jeans'), ('Pantalón', 'Pantalón'), ('Plumífero', 'Plumífero'), ('Sudadera', 'Sudadera'), ('Top', 'Top'), ('Vestido', 'Vestido'), ('Zapatos', 'Zapatos')], default=' ', max_length=100),
        ),
    ]
