# Generated by Django 3.2.8 on 2021-12-03 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outfitShowroomApp', '0004_auto_20211203_0823'),
    ]

    operations = [
        migrations.CreateModel(
            name='outfitShowroom',
            fields=[
                ('id_out', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=4000)),
                ('desc', models.CharField(max_length=4000)),
            ],
        ),
    ]
