# Generated by Django 3.2.8 on 2021-12-03 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outfitShowroomApp', '0005_outfitshowroom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outfitshowroom',
            old_name='desc',
            new_name='eslogan',
        ),
    ]
