# Generated by Django 3.2.8 on 2021-12-10 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outfitShowroomApp', '0006_rename_desc_outfitshowroom_eslogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='estilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estilo', to='outfitShowroomApp.estilo'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='ocasiones',
            field=models.ManyToManyField(related_name='estilos', to='outfitShowroomApp.Ocasion'),
        ),
        migrations.AlterField(
            model_name='outfit',
            name='prendas',
            field=models.ManyToManyField(related_name='prendas', to='outfitShowroomApp.Prenda'),
        ),
    ]
